"""Translate 401280's scalar data initialization into editable C++ constants.

No executable bytes are emitted. Every assignment or zero-fill in the recovered
initializer must be consumed, and each byte of the 50 records must be assigned.
"""
import hashlib,pathlib,re,struct,sys
ROOT=pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'.cache/binary_python'))
import pefile
path=pathlib.Path(r'E:\BaiduNetdiskDownload\PCGAME-Touhou.Kinjoukyou.Fossilized.Wonders-P2P\Touhou.Kinjoukyou.Fossilized.Wonders\th20.exe')
raw=path.read_bytes()
assert hashlib.sha256(raw).hexdigest()=='a274b45fe6ec53511718bb328c2ff169a74e67f95d1b0c74d97d348b955a0897'
pe=pefile.PE(data=raw)
first,last=0x5c06a8,0x5c49d8
data=bytearray(last-first);written=bytearray(len(data))
for line in (ROOT/'analysis/ghidra/pseudocode/00401280.c').read_text().splitlines():
    line=line.strip()
    if line.startswith('_DAT_'):
        match=re.fullmatch(r'_DAT_([0-9a-f]+) = (DAT_[0-9a-f]+|0x[0-9a-f]+|[0-9]+);',line)
        assert match,line
        dest=int(match[1],16);rhs=match[2]
        value=pe.get_data(int(rhs[4:],16)-0x400000,4) if rhs.startswith('DAT_') else struct.pack('<I',int(rhs,0))
    elif line.startswith('_memset'):
        match=re.fullmatch(r'_memset\(&DAT_([0-9a-f]+),0,(0x[0-9a-f]+)\);',line)
        assert match,line
        dest=int(match[1],16);value=bytes(int(match[2],0))
    else:continue
    offset=dest-first
    assert offset>=0 and offset+len(value)<=len(data)
    data[offset:offset+len(value)]=value;written[offset:offset+len(value)]=bytes([1])*len(value)
assert all(written) and len(data)==50*0x158
words=struct.unpack('<'+str(len(data)//4)+'I',data)
out=['// Data-only translation of original initializer 401280; generated by tools/recover_bullet_styles.py.',
     '#include "style.hpp"','#include <bit>','namespace th20::source::bullet {','const Style styles[50]={']
for i in range(50):
    row=words[i*86:(i+1)*86]
    out.append('    {0x%xu,{ // type %d'%(row[0],i))
    for j in range(16):out.append('        {{'+','.join('0x%08xu'%v for v in row[1+j*5:6+j*5])+'}},')
    out.append('    },std::bit_cast<float>(0x%08xu),%s},'%(row[81],','.join('0x%xu'%v for v in row[82:])))
out.extend(['};','float bullet_radius(std::int32_t type){return styles[type].radius;} //485700','}'])
(ROOT/'source_reconstruction/bullet_system/style_data.cpp').write_text('\n'.join(out)+'\n',encoding='utf8')
print(f'Recovered {len(data)} bytes in 50 editable data records; sha256={hashlib.sha256(data).hexdigest()}')
